steps:
  # running docker-compose
  - name: 'docker/compose:latest'
    args: ['up', '-d']
images: ['location/project/subtitler/bot', 'location/project/subtitler/server', 'location/project/subtitler/nginx']

options:
  logging: CLOUD_LOGGING_ONLY